import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Softjit Singh -Portfolio",
  description: "Generated by create next app",
   icons: {
    icon: 'https://github.com/SOFTJIT-SINGH/icons/blob/main/ICONS/Gemini%20alpha.png?raw=true',
    apple: '/apple-touch-icon.png',
    shortcut:
      'https://github.com/SOFTJIT-SINGH/icons/blob/main/ICONS/Gemini%20alpha.png?raw=true',
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
